export const FETCH_COMMANDES_REQUEST = 'FETCH_COMMANDES_REQUEST';
export const FETCH_COMMANDES_SUCCESS = 'FETCH_COMMANDES_SUCCESS';
export const FETCH_COMMANDES_FAIL = 'FETCH_COMMANDES_FAIL';
export const FETCH_COMMANDE_REQUEST = 'FETCH_COMMANDE_REQUEST';
export const FETCH_COMMANDE_SUCCESS = 'FETCH_COMMANDE_SUCCESS';
export const FETCH_COMMANDE_FAIL = 'FETCH_COMMANDE_FAIL';
export const ADD_COMMANDE_SUCCESS = 'ADD_COMMANDE_SUCCESS';
export const UPDATE_COMMANDE_STATUS_SUCCESS = 'UPDATE_COMMANDE_STATUS_SUCCESS';